name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "yarn"
          registry-url: "https://registry.npmjs.org"

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Yarn 4
        run: corepack prepare yarn@4 --activate

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test

      - name: Build the project
        run: yarn build

      - name: Validate build
        run: yarn validate:build

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ## Changes in this Release

            - Built with Rollup for optimized dual-format output
            - CommonJS and ESM bundles available
            - Global installation support via npm

            ## Installation

            ```bash
            npm install -g @coderrob/backstage-mcp-server
            ```

            ## Usage

            ```bash
            backstage-mcp-server
            ```
          draft: false
          prerelease: false
